sudo: required
services:
  - docker

before_install: 
  - docker build -t shubhmane99/react-test -f ./client/Dockerfile.dev ./client     #--- here we use docker dev file for run the test becuase we cant use prod docker file to run test

script: 
  - docker run -e CI=true shubhmane99/react-test npm run test

after_success:  # build prodcution docker files 
  - docker build -t shubhmane99/multi-client ./client  
  - docker build -t shubhmane99/multi-nginx ./nginx 
  - docker build -t shubhmane99/multi-server ./server 
  - docker build -t shubhmane99/multi-worker ./worker  
# login to docker cli for login we need username and password of docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# we will store this in travis environment variable setting
# take those images and push them to docker hub #
  - docker push shubhmane99/multi-client
  - docker push shubhmane99/multi-nginx
  - docker push shubhmane99/multi-server
  - docker push shubhmane99/multi-worker
